### ISSUE TITLE
Theme will not load

### ISSUE THREAD

**Issue by sabazk** [Torone/GhosToro#1]
Theme loads in general settings, but what i end up with is an unstyled page.
Went by instructions
unziped zip to content/themes
went to dev, npm install, grunt (edited gruntfile.js commented out watch in default task)
delete node_modules
load in general settings (works fine)
check page -- unstyled?

**Comment by Torone** [comment]
Hi,

It was a problem I recently fixed caused by the handlebars file minification.
On GIT there is a working copy that is running also [here](http://178.62.113.88:8880).
Sorry for late answer.

Best,
Andrea

**Comment by sabazk** [comment]
Cool thank you !

**Comment by Torone** [comment]
Let me know if you still have problems with it. Cheers!
